roles/epel/defaults/main.yml
roles/epel/tasks/main.yml

It also contains check to forbid this functionality on RHEL.

role epel: allow enable repo on CentOS

---

qe_server.yml
qe_server_jenkins.yml
roles/qe-server-user/README.rst
roles/qe-server-user/tasks/main.yml

Moving user tasks from qe server playbook into new ansible role for jenkins slave playbook to reuse it.

QE Server setup tweaks for jenkins slave

---

firewall.tendrl_gluster.workaround.yml
qe_gluster_firewall.yml

This is just workaround, there needs to be proper firewall configuration.

Configure firewall on test machines (workaround)

---

roles/qe-gluster-bricks/defaults/main.yml
roles/qe-gluster-bricks/tasks/main.yml
roles/qe-gluster-volume/defaults/main.yml
roles/qe-gluster-volume/tasks/main.yml

Added roles for automatic bricks and volume creation.

Gluster bricks and volume roles

---

gluster_peers_bricks.yml

This is just WORKAROUND, before we will have proper firewall configuration!

WORKAROUND: disable firewall during gluster cluster configuration

---

.travis.yml
.yamllint
README.rst
roles/tendrl-frontend/tasks/source.yml

Add yamllint configuration based on one from ansible project and configure Travis CI to run this check on every commit.

yamllint check

---

roles/tendrl-common/tasks/source.yml
roles/tendrl-devel/tasks/main.yml
roles/tendrl-performance-monitoring/README.rst
roles/tendrl-performance-monitoring/defaults/main.yml
roles/tendrl-performance-monitoring/meta/main.yml
roles/tendrl-performance-monitoring/tasks/binary.yml
roles/tendrl-performance-monitoring/tasks/main.yml
roles/tendrl-performance-monitoring/tasks/source.yml
tendrl_gluster.yml

add tendrl-performance-monitoring role, add openssl-devel as prerequisity

add tendrl-performance-monitoring role

---

roles/tendrl-alerting/README.rst
roles/tendrl-alerting/defaults/main.yml
roles/tendrl-alerting/meta/main.yml
roles/tendrl-alerting/tasks/binary.yml
roles/tendrl-alerting/tasks/main.yml
roles/tendrl-alerting/tasks/source.yml
roles/tendrl-common/tasks/source.yml

add tendrl-alerting role

---

roles/tendrl-performance-monitoring/tasks/source.yml

remove tendrl.conf copy from source installation

fix tendrl.conf copy

---

roles/qe-server/tasks/main.yml

qe-server role: Ignore errors when configuring firewall.

---

ceph_ansible.yml
ceph_prereq.yml
roles/ceph-ansible/README.rst
roles/ceph-ansible/tasks/main.yml

- Prepare environment for ceph.
- fix issues with ceph-ansible role

Ceph installation

---

ci_default.yml
gluster.yml
tendrl_ceph.yml
tendrl_gluster_peers_bricks.yml
tendrl_node.yml
tendrl_server.yml

And add default playbook for CI environment.

Split tendrl_gluster.yml to separated playbooks for tendrl and glusteror ceph

---

qe_pre_installation_tasks.yml

not all, because it conflict with qe_server

Hotfix - qe_pre_installation_tasks: update packages on usm_server:usm_nodes

---

roles/tendrl-performance-monitoring/tasks/main.yml

documentation: https://github.com/Tendrl/performance-monitoring/blob/c048ee67aab182b4a6764fd36a3f85ccddd7cb71/doc/source/installation.rst
resolves https://github.com/Tendrl/api/issues/82

update performance monitoring according to new documentation

---

qe_pre_installation_tasks.yml

https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference/60ab08c13ec3240d247c71c0c6c9690ef8a47ecd

WORKAROUND qe_pre_installation_tasks: configure selinux to permissive mode

---

qe_server_jenkins.yml
roles/qe-server/README.rst
roles/qe-server/files/20_usmqe_sudoers
roles/qe-server/tasks/main.yml

This pull request configures sudo to allow usmqe group to do anything as root via sudo.

usmqe sudoers configuration

---

ci_default.yml
qe_reboot.yml

Adding playbook for rebooting all machines (usable mainly after machine upgrade).

qe_reboot playbook

---

qe_pre_installation_tasks.yml
qe_tools.yml

For example:
- bind-utils
- git
- psmisc
- tmux
- tree
- vim

Separated playbook for installation of usefull tools.

---

roles/etcd/tasks/main.yml

based on https://github.com/Tendrl/documentation/pull/69/ but I think it is OK to merge it before 
https://github.com/Tendrl/documentation/pull/69 is merged.

add configuration options for etcd 

---

.gitignore
library/tendrl_user.py
qe_tendrl_admin.yml
roles/tendrl-api/tasks/main.yml
templates/usm.ini.j2
tendrl_admin.yml
tendrl_server.yml

Tendrl-api role now loads default admin user.
tendrl_server playbook now creates usm.ini configuration file.
There is ansible module for changing password for user from usm.ini in library.
There is playbook tendrl_admin for changing password for admin user from usm.ini for manual testing.

Admin user

---

roles/qe-server/tasks/main.yml

Add _wget_ and _createrepo_ between other installed tools.
Sort list of installed packages.

Qe server other tools

---

ci_default.yml
ci_tendrl_cluster.yml

https://github.com/Tendrl/api/issues/86
It also resolves https://github.com/Tendrl/usmqe-setup/issues/58.

remove tasks related to workaround

---

ci_default.yml
ci_tendrl_cluster.yml

Revert "remove tasks related to workaround"

---

ci_tendrl_cluster.yml
gluster.yml
roles/gluster-gdeploy-repo/README.rst
roles/gluster-gdeploy-repo/tasks/main.yml
tendrl_gluster.yml

This change is based on documentation change: https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference/_compare/7251f8d8ba5e203953681f90438359a7ac90292c...e395971bb84c5b9308844cf9a5e0ee5c97516c43

add gdeploy repo

---

firewall_tendrl.yml
qe_pre_installation_tasks.yml
qe_tools.yml
roles/ceph-centos-repo/tasks/main.yml
roles/ceph-installer/tasks/main.yml
roles/etcd/tasks/main.yml
roles/gluster-centos/tasks/main.yml
roles/qe-evidence-probe-journald/tasks/main.yml
roles/qe-evidence-probe/tasks/main.yml
roles/qe-server/tasks/main.yml
roles/rh-python35/tasks/main.yml
roles/tendrl-api/tasks/binary.yml
roles/tendrl-api/tasks/source.yml
roles/tendrl-ceph-integration/tasks/binary.yml
roles/tendrl-commons/tasks/binary.yml
roles/tendrl-dashboard/tasks/binary.yml
roles/tendrl-dashboard/tasks/source.yml
roles/tendrl-devel/tasks/main.yml
roles/tendrl-gluster-integration/tasks/binary.yml
roles/tendrl-node-agent/tasks/binary.yml
roles/tendrl-node-agent/tasks/source.yml
roles/tendrl-node-monitoring/tasks/binary.yml
roles/tendrl-performance-monitoring/tasks/binary.yml

Try each package installation via yum 5 times (if failing).

retry failed package installation

---

ci_default.yml
ci_default_import.yml

Add user tendrl-user
WORKAROUND for https://bugzilla.redhat.com/show_bug.cgi?id=1456552#c5
TODO: delete after resolving

add manually user tendrl-user

---

README.rst
roles/qe-server-user/defaults/main.yml

Updating urls of usmqe-* repositories.

update repo urls after usmqe* move

---

tendrl_unit_test_setup.yml

Add playbook that sets machine up for unit testing.

add tendrl_unit_test_setup.yml

---

qe_server.yml
roles/qe-server/tasks/main.yml

Make sure EPEL repository is enabled on QE Server, add `jq` tool into package list of qe server role.

Fix qe server

---

tendrl.yml

* remove Tendrl Performance Monitoring installation
* disable ceph-installer installation
* add Grafana repo

Changes for v1.5.0

---

roles/qe-tendrl-repo/defaults/main.yml
roles/qe-tendrl-repo/tasks/main.yml
roles/qe-tendrl-repo/vars/main.yml

- add possibility to select Tendrl repo configuration from predefined list (release, master)

qe-tendrl-repo: make repos selectable

---

tendrl.yml

* ensure that tendrl-monitoring-integration is started

WORKAROUND Tendrl/monitoring-integration/issues/33

---

qe_munin_node.yml
roles/qe-munin-node/README.rst
roles/qe-munin-node/defaults/main.yml
roles/qe-munin-node/handlers/main.yml
roles/qe-munin-node/tasks/main.yml

- install and configure munin-node

add qe-munin-node role and related playbook

---

qe_pre_installation_tasks.yml

This just installs, starts and enables chrony.

make sure time is synced via chrony

---

tendrl.yml

tendrl.yml: configure etcd_fqdn and graphite_fqdn

changes for 1.5.3

---

tendrl.yml

cleanup tendrl.yml playbook

---

roles/gluster-server/tasks/main.yml

* RHEL documentation states to install redhat-storage-server package (not only glusterfs-server)

install Gluster Server on RHEL accordingly to doc

---

test_setup.smtp.yml
test_teardown.smtp.yml

Test setup and teardown for email alerting test cases.

test setup for smtp alerting

---

test_setup.splitbrain.yml
test_teardown.splitbrain.yml

Playbooks to invoke split brain on 2 way replicated volume. Functionality verified during work on https://usmqe-testdoc.readthedocs.io/en/latest/web/alerting/glusternative_subvolume.html

splitbrain setup and teardown playbook

---

qe_pre_installation_tasks.yml
tendrl_unit_test_setup.yml

This reverts commit 3945a6f1a383fbb7682fb21ac6ff0b24e04db61f.
Fix https://github.com/usmqe/usmqe-setup/issues/50

remove WORKAROUND: configure selinux to permissive

---

qe_evidence.tendrl.yml

Evidence playbook update for tendrl, gluster and ceph.

Evidence playbook update

---

gluster.yml
roles/firewall-gluster/tasks/main.yml

* add firewall-gluster role
* configure firewall for gluster in gluster.yml

Configure firewall for Gluster

---

qe_pre_installation_tasks.yml

controlled by following variables  (containing comma separated list of urls pointing to repo config files)
- `additional_repos`
- `additional_repos_usm_server`
- `additional_repos_usm_nodes`
- `additional_repos_usm_client`

add any additional repo(s) if required

---

templates/usm.ini.j2

Used by valid_trusted_pool_reuse test fixture. 
https://github.com/usmqe/usmqe-tests/blob/master/usmqe_tests/api/gluster/conftest.py#L36

add usm_id_fqdn attribute to usm.ini template

---

bin/ansible2gdeploy.py

- add possibility to edit multiple files at once
- allow change storage devices (`-s/--storage-devices parameter`)

Enhance ansible2gdeploy

---

qe_server.yml
qe_server_jenkins.yml
roles/qe-server-user/tasks/main.yml
roles/qe-server/meta/main.yml
roles/qe-server/tasks/main.yml
roles/rh-python36/README.rst
roles/rh-python36/tasks/main.yml

This pull request changes Python used for test execution to python 3.6.

Switch to Python 3.6

---

README.rst
group_vars/README.rst
library/README.rst
roles/README.rst

Simplify main README file and add README files for few ansible directories, to keep the main readme short.

Update Readme files

---

ci_default_pre_tendrl.yml
firewall.tendrl.yml
qe_pre_installation_tasks.yml
qe_tools.tmux_mbukatov.yml
qe_tools.yml
roles/ceph-centos-repo/tasks/main.yml
roles/epel/tasks/main.yml
roles/firewall-gluster/tasks/main.yml
roles/gluster-client/tasks/main.yml
roles/gluster-server/tasks/main.yml
roles/qe-evidence-probe-journald/tasks/main.yml
roles/qe-evidence-probe/tasks/main.yml
roles/qe-munin-node/tasks/main.yml
roles/qe-server/tasks/main.yml
roles/rh-python35/tasks/main.yml
roles/rh-python36/tasks/main.yml

Changed "result|success" to "result is success" due to deprecation warnings from ansible.

Changed syntax, Issue #197

---

ci_default_post_tendrl.yml

add WORKAROUND: update ansible

---

test_setup.fips.yml

Fix https://github.com/usmqe/usmqe-setup/issues/206

Add  test setup playbook for FIPS mode

---

roles/gluster-centos-repo/README.rst

fix gluster-centos-repo README

update README with new versions of gluster

---

test_setup.clouduser.yml
test_setup.wiki_tarball.yml

This is the same issue as recently fixed tendrl-ansible https://github.com/Tendrl/tendrl-ansible/issues/124

fix asserts to be compatible with ansible 2.7

---

test_setup.fips.yml

Make it clear what FIPS configuration we are currently working with: dropping WA server from fips setup playbook.

Cleanup fips

---

qe_pre_installation_tasks.yml
roles/qe-server/tasks/main.yml

Make sure that `atd` is running because of https://github.com/usmqe/usmqe-tests/pull/215.

start and enable atd

---

test_setup.gluster_volume_stop.yml
test_teardown.gluster_volume_stop.yml

Stopping all volumes. Used in tests related to volume behaviour.

Stop volume

---

roles/qe-server-user/tasks/main.yml
roles/qe-server/tasks/main.yml

Minimal changes to get taretto tests working.

tweaking setup for web tests

---

roles/qe-evidence-probe-journald/tasks/main.yml
roles/qe-evidence-probe/tasks/main.yml
roles/qe-evidence/tasks/main.yml

improve error messages for evidence probes

improve error messages for evidence probles

---

bin/usmqe_alerts_logger.py
test_setup.alerts_logger.yml

Without this, reconfiguration is not possible.

restart handler for alerts_logger setup
