usmqe/usmqe-setup

roles/rh-python35/tasks/main.yml

Package centos-release-scl is available only on CentOS machine, not applicable on RHEL.

rh-python35 on RHEL 7 machine

---

roles/qe-server-user/defaults/main.yml
roles/qe-server-user/tasks/main.yml

I have added installation of Jonathan's ansible gluster module and moved both url and versions of git repositories into variables, which would allow ah hoc tweaking if needed.

Update qe server setup for CI

---

roles/qe-server-user/tasks/main.yml

role qe-server: wrap variable by quotes for backward compatibility with ansible 1.9

role qe-server: wrap variable by quotes for backward compatibility

---

qe_pre_installation_tasks.yml
tendrl_gluster_peers_bricks.yml

Added qe_pre_installation_tasks.yml playbook for such auxiliary pre-installation tasks, such as package update.

Add qe_pre_installation_tasks.yml playbook for auxiliary pre-installation tasks, such as package update.

---

roles/tendrl-gluster-integration/tasks/main.yml

Drop `tendrl-gluster-integration` service starting according to:
https://github.com/Tendrl/gluster-integration/issues/148#issuecomment-281998249
Add `gstatus` installation because of:
https://github.com/Tendrl/gluster-integration/issues/151
`gstatus` installation should be removed after the issue is resolved.

Update tendrl-gluster-integration role

---

qe_evidence.journald_export_example.yml
roles/qe-evidence-probe-journald/README.rst
roles/qe-evidence-probe-journald/defaults/main.yml
roles/qe-evidence-probe-journald/tasks/main.yml

This role downloads exports from journald log database for given systemd
services.
Resolves https://github.com/Tendrl/usmqe-setup/issues/48

role qe-evidence-probe-journald

---

ceph_ansible.yml

This pull request fixes https://github.com/Tendrl/usmqe-setup/issues/43 by allowing usmqe user to become root via sudo and using this power to execute `ceph-ansible` role locally under root user.

Fix ceph ansible local

---

roles/epel/tasks/main.yml

This might fix problem with downloading epel-release-latest-7.noarch.rpm package like this:
```
fatal: [ci-usm2-gl1.localdomain]: FAILED! => {
"changed": false, 
"failed": true, 
"invocation": {
"module_args": {
"conf_file": null, 
"disable_gpg_check": false, 
"disablerepo": null, 
"enablerepo": null, 
"exclude": null, 
"install_repoquery": true, 
"list": null, 
"name": [
"https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
], 
"state": "present", 
"update_cache": false, 
"validate_certs": true
}, 
"module_name": "yum"
}, 
"msg": "Failure downloading https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm, 'NoneType' object has no attribute 'read'"
}
```

Retries epel package installation.

---

ci_default.yml

based on:
https://github.com/Tendrl/api/issues/86#issuecomment-285063914
TODO: remove this after issue resolution

workaround for https://github.com/Tendrl/api/issues/86

---

ci_default.yml
tendrl_gluster_peers_bricks.yml

`tendrl-ceph-integration` and `tendrl-gluster-integration` roles are going to be removed from tendrl installation playbooks. `tendrl-node-agent` should install them.
Based on:
https://github.com/Tendrl/gluster-integration/issues/133#issuecomment-288409086
https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference

remove tendrl-{ceph, gluster}-integration roles from playbooks

---

ci_default.yml

Workaround for https://github.com/ceph/ceph-ansible/issues/1403

WORKAROUND: run partprobe on ceph OSD nodes

---

ceph_prereq.yml
gluster.yml
gluster_peers_bricks.yml
roles/ceph-centos-repo/README.rst
roles/ceph-centos-repo/defaults/main.yml
roles/ceph-centos-repo/tasks/main.yml
roles/gluster-centos-repo/README.rst
roles/gluster-centos-repo/defaults/main.yml
roles/gluster-centos-repo/tasks/main.yml
roles/gluster-centos/defaults/main.yml
roles/gluster-centos/tasks/main.yml

We need to have separated playbooks or roles for configuring Ceph and Gluster repo, because Tendrl should be able to install Ceph and Gluster cluster itself but it requires the proper repositories configured.

Separate Ceph and Gluster repos to new playbooks

---

ci_tendrl_cluster.yml

This playbook perform following tasks, when applicable (e.g. there are nodes in gluster or ceph_* group)
* Configure firewall
* Install Tendrl server.
* Install Tendrl storage nodes.
* Add Gluster repo.
* Add Ceph repos.

ci_tendrl_cluster.yml: playbook for installation of tendrl cluster without Ceph or Gluster cluster

---

roles/ceph-installer-repo/README.rst
roles/ceph-installer-repo/tasks/main.yml
roles/ceph-installer/README.rst
roles/ceph-installer/tasks/main.yml
roles/tendrl-node-agent/tasks/main.yml
tendrl_server.yml

Install ceph-installer on Tendrl server.
Install tendrl-node-agent on Tendrl server.
Configure proper tags for tendrl-node-agent on Tendrl server.

Tendrl release v1.2.2 updates

---

tendrl_ceph.yml
tendrl_gluster.yml
tendrl_node.yml
tendrl_server.yml

Since Tendrl itself finally starts to cover package installation to some
degree, we need to have epel enabled from now on for this to work.
Note: when you run these playbooks on RHEL, the setup fails - there is
no change in the check. This is a feature: enabling EPEL in such case
is a blocker bug and we need to catch it as soon as possible.
Based on @mkudlej feedback.

re-enable epel repository

---

qe_tendrl_admin.yml
roles/tendrl-api/tasks/main.yml

The admin password is stored in `/root/password` file without the ending new line:
```
8b725666[root@usm-server ~]# 
```
This patch will add new line at the end of the password file.

tendrl-api: add new line to password file

---

roles/ceph-ansible/tasks/main.yml

- use interface and network address from first monitor
(instead of qe_server)

fix ceph-ansible network configuration

---

roles/gluster-gdeploy-repo/tasks/main.yml

Use http protocol for gdeploy repo and gpg key to allow proxy caching.

gdeploy repo: use http instead https

---

ceph_ansible.yml
roles/ceph-ansible/tasks/main.yml

* configure second configured network as Ceph cluster_network (if available).
* calculate network prefix via jinja2 filter (instead of previously used `ipcalc` command)

Ceph-ansible add support for cluster_network

---

roles/qe-server/tasks/main.yml

* python-netaddr is required for ipaddr jinja2 filter

Install python-netaddr on qe_server

---

roles/gluster-centos/README.rst
roles/gluster-centos/tasks/main.yml

This adds enabling `glusterd` service after glusterfs is installed and `glusterd` started.

enable glusterd service

---

roles/tendrl-api/tasks/main.yml
roles/tendrl-performance-monitoring/tasks/main.yml

* use ansible_default_ipv4 instead of specific ansible_eth0.ipv4

Allow different default NIC name (not only eth0).

---

ci_default.yml

Thanks to this change we should be able to import gluster cluster. For ceph cluster @dahorak needs to create workaround.

switch node-agent install task with cluster creation

---

ci_default.yml
ci_default_import.yml

* rename ci_tendrl_cluster.yml to ci_default.yml
- install and configure Tendrl server and nodes
- do not install and configure Ceph or Gluster
- usable for cluster creation via Tendrl API/UI
* rename ci_default.yml to ci_default_import.yml
- install and configure Tendrl server and nodes
- install and configure Ceph or/and Gluster cluster
- usable for cluster import testing via Tendrl API/UI

Update main ci_* playbooks structure

---

ci_default.yml
ci_default_import.yml

This removes restarting node-agent as it is not described in any installation documentation. It was supposed to resolve issue with not detected cluster according to https://github.com/Tendrl/api/issues/86#issuecomment-285063914.
Cluster is now detected without restarting node-agent. This will resolve inactivity of `tendrl-node-monitoring` service. (https://github.com/Tendrl/dashboard/issues/361#issuecomment-303934353)

remove workaround

---

ci_default_import.yml
gluster_peers.yml

* in ci_default_import playbook only create gluster trusted storage
pool, do not create bricks (pre-created bricks are not recognized by
Tendrl).

add and use gluster_peers playbook

---

roles/ceph-ansible/tasks/main.yml

There is no need for having calamari on mons because tendr-ceph-instegration is calamari fork.

remove calamari instllation

---

tendrl_server.yml

Adds installation of `tendrl-alerting` on tendrl server.

add tendrl-alerting role to tendrl_server.yml playbook

---

roles/tendrl-api/tasks/main.yml

According to PR https://github.com/Tendrl/api/pull/196

rename tendrl-apid service to tendrl-api

---

qe_evidence.example.yml
qe_evidence.tendrl.yml
qe_evidence.yml
roles/qe-evidence-probe/files/tendrl-devel-debug.py
roles/qe-evidence-probe/tasks/main.yml
roles/qe-evidence/tasks/main.yml

This update of envidence playbook for Tendrl includes:
* extend evidence probe role to provide all details in particular format as documented in https://github.com/Tendrl/documentation/wiki/Information-required-for-debugging-issues-on-the-Tendrl-stack
* fix of checksum issue
* list of directories and files were updated
Example of usage:
```
$ ansible-playbook -i mbukatov-usm1.hosts qe_evidence.tendrl.yml  --extra-vars='evidence_target=/home/martin/tmp/evidence-foo'
$ cd ~/tmp/evidence-foo
$ ls
mbukatov-usm1-gl1.example.com  mbukatov-usm1-mon1.example.com  mbukatov-usm1-osd2.example.com
mbukatov-usm1-gl2.example.com  mbukatov-usm1-mon2.example.com  mbukatov-usm1-osd3.example.com
mbukatov-usm1-gl3.example.com  mbukatov-usm1-mon3.example.com  mbukatov-usm1-osd4.example.com …
```

Update evidence playbook for tendrl

---

tendrl.yml

This fixes an issue with missing `provisioner/gluster` tag on gluster storage nodes.

fix issue with missing 'provisioner/gluster' tag

---

tendrl.yml

Installation of *Tendrl Performance Monitoring* is done only on machines in `usm_perfmon` ansible inventory group, so that installation of dedicated monitoring machine is possible. To continue using collocated Tendrl Server with Monitoring, add the server machine into this new group.

support for dedicated perf mon machine

---

roles/qe-server-user/tasks/main.yml
roles/qe-server/tasks/main.yml

Since pylatest requires more recent version of sphinx compared to what
is provided in el7, we install just python-lxml and python-docutils from
rpm packages and then under usmqe user account, install pylatest via pip
into ~/.local/lib/python2.7/ directory.

qe_server: install pylatest

---

gluster.yml
roles/gluster-centos-repo/README.rst
roles/gluster-centos-repo/defaults/main.yml
roles/gluster-centos-repo/meta/main.yml
roles/gluster-centos-repo/tasks/main.yml
roles/gluster-centos-repo/vars/main.yml
roles/gluster-centos/README.rst
roles/gluster-centos/tasks/main.yml

This pull request fixes a rotten gluster setup roles by:
* specifying particular glusterfs releases we can use with the role
* fix wrong way to handle the fact that Storage SIG packages are unsigned
* enable nightly glusterfs builds by default (as suggested by tendrl devs)
* linking to maintainers of the gluster repositories
* removing unnecessary packages during glusterfs installation

Fix gluster repository setup and package installation

---

qe_pre_installation_tasks.yml
qe_reboot.yml
qe_tools.yml

We are missing few common setup steps on a client machine, this commit fixes the problem.

add client role to general setup playbooks

---

roles/qe-munin-node/tasks/main.yml

Use ansible `inventory_hostname` as munin `host_name` configuration variable on *non USM* VMs.

configure munin-node hostname on non USM VMs

---

.gitignore
qe_get_tendrl_ansible.yml
tendrl.yml

add `qe_get_tendrl_ansible.yml` playbook:
- get tendrl-ansible package and unpack it to local directory
(by default `./tendrl-ansible-tmp/`)
- add the default *tendrl_ansible_dir* (`./tendrl-ansible-tmp/`) to
`.gitignore`
rename used tendrl-ansible roles:
- roles from tendrl-ansible package are prefixed by `tendrl-ansible.`

Use tendrl-ansible roles from package

---

tendrl_unit_test_setup.yml

* tendrl_unit_test_setup: enable gluster repo because of gluster dependencies for tendrl-gluster-integration
* do not install tendrl-node-selinux because of conflict with tendrl-server-selinux

rpm validation setup: update for 1.5.2

---

qe_ssl_certs.etcd.yml
tendrl.yml

Setup for etcd tls client server authentication:
* new dedicated playbook for just this task
* included into tednrl.yml playbook as well (it's enabled there by default)

Etcd tls auth

---

tendrl_unit_test_setup.yml

both tendrl-server-selinux and tendrl-node-selinux packages are replaced by tendrl-selinux package

unit test setup: exclude tendrl-server-selinux

---

qe_get_tendrl_ansible.yml
qe_reboot.yml
tendrl.yml

Playbooks tendrl.yml,  qe-tendrl-repo.yml: add condition for adding upstream repos (add upstream repos only on CentOS)
This change will allow usage of of the playbooks on both CentOS and RHEL.

add upstream repos only on CentOS

---

roles/epel/tasks/main.yml
roles/qe-server/meta/main.yml

* allow epel on rhel, when `qe_not_production_testing_server` parameter is defined

make possible epel installation on rhel

---

roles/qe-server/tasks/main.yml

ceph-ansible package shouldn't be required on qe_server in this days

qe-server role: do not install ceph-ansible

---

firewall.tendrl.yml

* Port opened for tendrl-monitoring-integration should be 8789, not 8989.
* fix https://github.com/usmqe/usmqe-setup/issues/166

tendrl firewall: fix monitoring-integration port

---

tendrl_unit_test_setup.yml

because tendrl-monitoring-integration depends on "grafana < 4.5.3"
Fixing issue with preparation of test server for package validation (for example: https://ci.centos.org/view/tendrl-build-release/job/tendrl-pkgval-X-release-prepare/)

exclude grafana-4.6.* in tendrl_unit_test_setup.yml

---

tendrl.yml

- qe-ssl-cert role doesn't work in some environments which shouldn't
break the whole installation (if ssl is not requested)

create ssl-cert only if necessary

---

qe_munin_node.yml
roles/qe-munin-node/tasks/main.yml

Explicitly enable epel during munin-node installation.
This will fix issue with munin-node installation without installed Tendrl.

Fix munin node installation

---

test_setup.clouduser.yml
test_teardown.clouduser.yml

Adds setup and tear down playbook for environment when we don't have direct ssh root access on storage machines and need to connect via different user and then use sudo instead.

Test setup and teardown for cloud-user like access

---

tendrl_unit_test_setup.yml

This reverts commit 64d18e21f93f0d2c247052b54b3055419c168317.
Fixes https://github.com/usmqe/usmqe-setup/issues/171

Revert "WORKAROUND: exclude grafana-4.6.*"

---

bin/ansible2gdeploy.py

* add parameter `-h`/`--host-definition {fqdn,short,ip,mixed,random}` (default: `fqdn`)
Specifies how to define hosts in gdeploy config.

ansible2gdeploy - host specification type (fqdn, short name, ip, mixed, random)

---

bin/ansible2gdeploy.py

- add arguments `--gluster-server-group` and `--gluster-client-group` for
configuration of Ansible inventory group names used for Gluster
servers and clients

ansible2gdeploy: make ansible group names configurable

---

qe_reboot.yml

Add optional parameter `skip_reboot` to be able to skip machines reboot during the pre setup operations.

add possibility to skip reboot

---

bin/wiki-export-split.py
test_setup.wiki_tarball.yml
test_teardown.wiki_tarball.yml

This test setup playbook will download enwiki tarball (using url from variable in host inventory file)
and install `wiki-export-split.py` script into `/usr/local/bin` on the client machine.
Teardown just removes both files.

setup and teardown for wiki tarball

---

bin/ansible2gdeploy.py

This patch enables usage of `example.org` as a domain for some clusters instead of default available domain (usage of this configuration requires some additional steps on all of the hosts in the cluster).

Enable usage of example.org domain for hosts

---

roles/gluster-centos-repo/vars/main.yml

Add Gluster CentOS repos for versions 3.13, 4.0 and 4.1.

add new Gluster CentOS repos

---

ci_default_post_tendrl.yml

- when *ansible* is updated, restart related *tendrl-node-agent* service
- related to #202

WORKAROUND: restart tendrl-node-agent service

---

ci_default_pre_setup.yml

- run `test_setup.fips.yml` when `configure_fips` is set to `true` (or `yes`)

configure fips as part of pre setup script

---

qe_reboot.yml

- use better and more clear approach for reboot and wait for the machines to start
- usage of *async* task for reboot and *wait_for_connection* task

polish reboot process

---

gdeploy_config/volume_alpha_distrep_6x2.fips.conf
gdeploy_config/volume_beta_arbiter_2_plus_1x2.fips.conf
gdeploy_config/volume_gama_disperse_4_plus_2x2.fips.conf

This configures gluster volumes to use `fips-mode-rchecksum`.
Validation:
```
Option                                  Value                                   
------                                  -----                                   
storage.fips-mode-rchecksum             enable
```

add gdeploy config for fips mode

---

gdeploy_config/volume_alpha_distrep_6x2.fips.conf
gdeploy_config/volume_beta_arbiter_2_plus_1x2.fips.conf
gdeploy_config/volume_gama_disperse_4_plus_2x2.fips.conf

Right now, this bugzilla is the only reference for `fips-mode-rchecksum` option.

reference bugzilla for fips gluster option

---

test_setup.fips.yml

This is done to workaround know issue with snmp alerting and FIPS mode,
see:
* https://bugzilla.redhat.com/show_bug.cgi?id=1640638
* https://bugzilla.redhat.com/show_bug.cgi?id=1513066

test setup fips: don't enable fips on client

---

test_setup.graphite_access.yml
test_teardown.graphite_access.yml

- add setup and teardown playbooks to allow access to Graphite from tests (on port 60080/tcp).

add test_{setup,teardown}.graphite_access.yml playbooks

---

ci_default_pre_setup.yml

- epel is now required to be enabled before tendrl-ansible installation
on tendrl_server
- fixing https://github.com/Tendrl/commons/pull/1055#issuecomment-420184234
- this apply only for upstream (CentOS) installation

add epel as part of pre setup procedure

---

roles/qe-server/tasks/main.yml

We will have both firefox and chromium available on qe server.
Chromium was added because initial version of our tarreto based web
tests requires chromium, see:
https://github.com/usmqe/usmqe-tests/pull/217
Chromium is installed from EPEL 7.

qe-server: install chromium for web tests

---

roles/tendrl-httpd-ssl/tasks/main.yml
test_teardown.tendrl_httpd_ssl.yml

This change is based on:
* https://github.com/Tendrl/api/issues/458 (rename Rename tendrl-ssl.conf.sample)
* https://github.com/Tendrl/api/issues/460 (Change redirect directive, VirtualHost `_default_`)
* ssl setup wikipage: https://github.com/Tendrl/documentation/wiki/Enabling-Https-on-tendrl-server

implement changes in ssl setup

---

qe_server.yml
qe_server_jenkins.yml

* skip ssl configuration if skip_ssl_configuration is defined
(used in CentOS CI)
* remove previously added "skip" condition in qe_server_jenkins.yml
playbookk

qe_server: add possibility to skip ssl config

---

roles/qe-server/files/Xvfb.service
roles/qe-server/handlers/main.yml
roles/qe-server/tasks/main.yml

This is necessary for usmqe_tests.ui.test_host_ui.test_host_bricks to
navigate in web ui (volume name, which is quite long, was so short that
it can't be recognized in the original resolution).

increase resolution of Xvfb for web tests

---

roles/qe-ssl-cert/files/ssl_cert.sh

* ensure that generated ssl certs will use sha256 algorithm  instead of sha1
* related change on the *ooo* server is in `/etc/pki/tls/openssl.cnf`: set `default_md` to `sha256` (already in place)

ensure that generated ssl certs will use sha256 algorithm instead of sha1

---

roles/qe-ssl-cert/files/ssl_cert.sh

In OpenStack - PSI environment, `hostname` doesn't return fqdn but short
name which might not be properly resolved to back to IP.
Because of that, we will use `hostname -f` to get fqdn for IP
resolution.

Fix ssl_cert.sh - use fqnd to find IP address

---

configure_admin_email_notifications.yml
test_setup.alerts_logger.yml
test_setup.smtp.yml
test_teardown.smtp.yml

This expects that one specifies `tendrl_api_url_protocol: https` in the inventory file when https is enabled.
It is necessary for https://github.com/usmqe/usmqe-tests/pull/231

Tweak setup playbooks to work with https enabled Tendrl API

---

test_setup.tendrl_nodeagent_stopped_on_one_node.yml
test_teardown.tendrl_nodeagent_stopped_on_one_node.yml

These playbooks serve as a setup/teardown for negative test cases, such as import with cluster in an invalid state.

test setup: tendrl nodeagent stopped on one node
